# Global
exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
timezone: "Australia/Sydney"
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build
watch: true
incremental: true
strict_front_matter: true
permalink: /:slug/
sass:
  style: compressed

# Templates
title: goto null;
url: https://www.gotonull.com/
